   services:
     - type: web
       name: edgeroute
       env: python
       buildCommand: pip install -r requirements.txt
       startCommand: gunicorn wsgi:app
       envVars:
         - key: DATABASE_URL
           value: postgresql://edgeroute_user:KOUhEUE7NWIHsN3FM1mZNMANK5oCzh1P@dpg-d0id73be5dus7390v91g-a/edgeroute_6hdw
