"""Add supabase_id and remove password column

Revision ID: 282297331481
Revises: 
Create Date: 2025-05-14 15:35:22.729057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282297331481'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('supabase_id', sa.String(length=36), nullable=True),
    sa.Column('avatar', sa.String(length=20), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('supabase_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_node',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('roadmap_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('links', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.String(length=50), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.String(length=50), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['roadmap_node.id'], ),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.drop_table('roadmap_version')
    op.drop_table('roadmap_node')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('roadmap')
    # ### end Alembic commands ###
