"""Remove supabase_id column from User model

Revision ID: 9f55d46e6641
Revises: 59f4f0bf26cd
Create Date: 2025-05-14 22:05:38.616235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f55d46e6641'
down_revision = '59f4f0bf26cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.drop_column('supabase_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supabase_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.alter_column('_password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    # ### end Alembic commands ###
