[program:edgeroute]
directory=/var/www/edgeroute
command=/var/www/edgeroute/venv/bin/gunicorn --workers 4 --bind 127.0.0.1:5000 wsgi:app
autostart=true
autorestart=true
stderr_logfile=/var/log/edgeroute/edgeroute.err.log
stdout_logfile=/var/log/edgeroute/edgeroute.out.log
user=www-data
environment=FLASK_CONFIG=production

[group:edgeroute]
programs=edgeroute
